### ISSUE TITLE
Feature: Subfolder

### ISSUE THREAD

**Issue by marcobiedermann** [alanshaw/david#120]
It would be great to support multiple `package.json` files per repo.
E.g. I got an repo `playground` which contains multiple projects.
I would like to track each project individually.

```
REPO
- project-a
  - package.json
- project-b
  - package.json
```

This should be accessible as following:
https://david-dm.org/USER_NAME/REPO/PATH/TO/SUBFOLDER

**Comment by alanshaw** [comment]
This is already available e.g.
https://david-dm.org/alanshaw/non-root-package.json?path=src

**Comment by marcobiedermann** [comment]
@alanshaw Awesome, thanks man!

**Comment by Hongbo-Miao** [comment]
Hi @alanshaw based on this demo repo https://github.com/alanshaw/non-root-package.json.

Seems **david-dm** is picking
```
src/package.json
```
but ignored
```
src/test/package.json
```

So does that mean **david-dm** only pick the level that most close to root level and ignore the rest? Thanks
