### ISSUE TITLE
https://david-dm.org/ is down?

### ISSUE THREAD

**Issue by scippio** [alanshaw/david#133]
I'm trying access to https://david-dm.org/ but I get only:
```
504 Gateway Time-out

nginx/1.4.6 (Ubuntu)
```

**Comment by alanshaw** [comment]
please see https://github.com/alanshaw/david-www/issues/357#issuecomment-278117903

**Comment by alanshaw** [comment]
Closing as stability has resumed. Thanks for reporting.
