### ISSUE TITLE
Dependencies always in pending state

### ISSUE THREAD

**Issue by jeffminsungkim** [alanshaw/david#142]
Even though node modules are the latest version, still, the state remains pending for more 24 hours.

![screenshot 2018-03-26 15 56 41](https://user-images.githubusercontent.com/6092023/37891190-4ce14f2c-310e-11e8-848b-a0033144b2b6.png)

**Comment by alanshaw** [comment]
This is an issue with david-www, for which you've already commented. I'm closing this issue as a duplicate. Please could you provide the URL to your project so I can debug?

**Comment by jeffminsungkim** [comment]
Thanks for your response. Here's my [repo](https://github.com/jeffminsungkim/jeffminsungkim.com)
