### ISSUE TITLE
https://david-dm.org/ 502 Bad Gateway

### ISSUE THREAD

**Issue by mrodrig** [alanshaw/david#149]
It appears as though https://david-dm.org/ is down right now - throwing a 502 Bad Gateway error.

**Comment by isaachinman** [comment]
Any update on this? I would imagine it affects many, many projects.

**Comment by hodgef** [comment]
Dependecy status is showing invalid as a result. Any solution or alternative?
![image](https://user-images.githubusercontent.com/25509135/51724455-7af3ee80-202b-11e9-8eed-8cc1acac94f2.png)

**Comment by AnandChowdhary** [comment]
@alanshaw Maybe we can set up a CDN or a mirror service, which you can redirect to when this happens? It makes a lot of very popular repositories' READMEs look bad. 😢

**Comment by vweevers** [comment]
In case the issue is lack of funds, is there a patreon/paypal/other? I will happily donate.

**Comment by isaachinman** [comment]
Maybe a good place to start is a free CloudFlare plan?

**Comment by isaachinman** [comment]
Regardless of a CDN, the service is still returning 502s. What's the root issue?
