### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by hodgef** [alanshaw/david#150]
Hello @alanshaw,

David-dm seems to be currently down:

![image](https://user-images.githubusercontent.com/25509135/53342287-9dec1980-38db-11e9-9a0b-3aabc3f24aa1.png)

This results in statuses showing as invalid:
![image](https://user-images.githubusercontent.com/25509135/51724455-7af3ee80-202b-11e9-8eed-8cc1acac94f2.png)

Any idea on what might be causing tthis?

Error as per this closed item:
https://github.com/alanshaw/david/issues/149

**Comment by alanshaw** [comment]
I think it ran out of disk space this time

**Comment by hodgef** [comment]
Thanks for the quick fix ! Very appreciated
