### ISSUE TITLE
https://david-dm.org is down

### ISSUE THREAD

**Issue by SudharakaP** [alanshaw/david#153]
It seems the service (https://david-dm.org) is down for several days. I know it might not be cheap to host this and perhaps there's some kind of service disruptions; but does anybody know anything about this? I have seen this being intermittent but haven't seen this being down for several days. Is it permanently closed? 

![image](https://user-images.githubusercontent.com/12435965/61013393-3341f480-a337-11e9-9b86-339bec1e2885.png)

**Comment by Geo1088** [comment]
Getting the same issue as #150 here. 502 when visiting the website and my badges are showing as `dependencies | unavailable`.

**Comment by SudharakaP** [comment]
Seems that David is up again so I am making this as closed.
