### ISSUE TITLE
v11.1.0 appears to have been a breaking change in a minor version.

### ISSUE THREAD

**Issue by ljharb** [alanshaw/david#159]
- it removed nodes 4 - 7 from the test matrix
 - it upgraded async from v2 to v3, which drops support for node 4 and earlier
 - it upgraded npm from v4 to v6, which drops support for node versions below node 6
 - you added `multimatch`, and that author's deps all aggressively drop support for older nodes, and happens to require node 8+.

In this case, I'm not even *invoking* david in nvm's test suite; i'm just trying to *install* it on node 0.10. See https://travis-ci.org/nvm-sh/nvm/jobs/621428822 as an example.

For a tool that checks deps with semver, I'd hope for more semver compliance. Would you consider reverting all of these breaking changes in a v11 release, and rereleasing as a v12?

**Comment by alanshaw** [comment]
Yes I would, and I'm worry to have caused you pain.

I just checked out the v11 tag and there's test failures :(

**Comment by ljharb** [comment]
Presumably due to new versions of deps and/or dev deps since the release; you can use npm install’ `--before` option to install from a known good date and help spelunk it?

**Comment by alanshaw** [comment]
Does v11.1.1 work for you?

**Comment by ljharb** [comment]
It still seems to fail to install on 0.10 (i reran the jobs above)

**Comment by alanshaw** [comment]
I don’t understand that error...is that the same error as before?

**Comment by ljharb** [comment]
So to be fully honest i haven’t debugged it deeply - i noticed the Travis failure in 0.10 and then looked at your changelog to locate the breaking changes.

I’ll try to repro it locally and see if i can point to something more specific.

**Comment by ljharb** [comment]
Ah wait; you published a v12 also - those nvm tests don't constrain the version. Let me check that again.

**Comment by ljharb** [comment]
Thanks, v11.1.1 seems to have fixed it :-)
