### ISSUE TITLE
https://david-dm.org/ down?

### ISSUE THREAD

**Issue by abhijeetnarvekar** [alanshaw/david#161]
https://david-dm.org/ seems to be not working today

<img width="1125" alt="Screenshot 2020-01-03 at 10 32 19" src="https://user-images.githubusercontent.com/17494707/71716302-88595180-2e14-11ea-8e3d-596ffc878152.png">

<img width="1273" alt="Screenshot 2020-01-03 at 10 34 55" src="https://user-images.githubusercontent.com/17494707/71716355-ba6ab380-2e14-11ea-92bb-9c2e0a12a156.png">

Best.

**Comment by Geo1088** [comment]
Experiencing this as well :/

**Comment by abhijeetnarvekar** [comment]
Is resolved now. Thanks!
