### ISSUE TITLE
Badge URL resolving to a package.json

### ISSUE THREAD

**Issue by achingbrain** [alanshaw/david#162]
It would be great if the URLs behind badges could point directly to a package.json file.  This would enable supporting [lerna](https://github.com/lerna/lerna)-style monorepos.

Something like:

```markdown
![Babel Dependencies](https://github.com/babel/babel/blob/master/packages/babel-cli/package.json.svg)
```

**Comment by alanshaw** [comment]
Like this? https://david-dm.org/babel/babel?path=packages/babel-cli

https://davidiswatching.tumblr.com/post/132882415144/non-root-packagejson

...probably should be documented on the site.

**Comment by achingbrain** [comment]
Aha, yes - that’ll do it. Thanks!
