### ISSUE TITLE
https://david-dm.org is down

### ISSUE THREAD

**Issue by ltchris** [alanshaw/david#163]
Currently getting `502 Bad Gateway` errors.

**Comment by cedx** [comment]
Also today.

**Comment by borracciaBlu** [comment]
Down right now HTTP 502

**Comment by brettdorrans** [comment]
Is this project dead?

**Comment by muescha** [comment]
@lanshaw ?

**Comment by manferlo81** [comment]
It is down right now

**Comment by C0ZEN** [comment]
This is back online.

**Comment by slightlyfaulty** [comment]
@C0ZEN Not anymore apparently...

**Comment by patorjk** [comment]
Agreed. It's been down all day.

**Comment by DanielRuf** [comment]
I think in the longterm we may need a solution which is always available.
But I do not sure which alternatives we have.

**Comment by eine** [comment]
@DanielRuf, what about proposing GitHub to have this service integrated into dependabot?

**Comment by DanielRuf** [comment]
I'm not sure if GitHub would provide this.

At least we have a few more there: https://shields.io/category/dependencies

**Comment by DanielRuf** [comment]
Currently it seems to work again. But it's not sure for how long until the next time.

I miss some transparency about the availability, also in the future.

**Comment by alanshaw** [comment]
VM kept running out of disk space. I finally got a little time to resize from 20GB to 60GB so hopefully that should last for a while. I appreciate the pings when things go down. Please keep 'em coming :)

**Comment by DanielRuf** [comment]
It seems to be down again - same error (502 Bad gateway).
