### ISSUE TITLE
david-dm.org down?

### ISSUE THREAD

**Issue by DanielRuf** [alanshaw/david#171]
<img width="680" alt="Bildschirmfoto 2020-08-15 um 22 08 39" src="https://user-images.githubusercontent.com/827205/90320722-e3732b00-df43-11ea-9dd8-5060c0d1aec3.png">

I guess it is finally down forever?

**Comment by DanielRuf** [comment]
It seems to work again without further notice.

So I'm closing this as resolved. So far I've removed the badge as I think there is not much reason to keep it when David is down so often so we can not see the detail then and there is no public statement or status page.

<img width="890" alt="Bildschirmfoto 2020-08-16 um 22 30 53" src="https://user-images.githubusercontent.com/827205/90343404-5c3fb900-e010-11ea-84ec-62c15a324129.png">

<img width="965" alt="Bildschirmfoto 2020-08-16 um 22 32 46" src="https://user-images.githubusercontent.com/827205/90343420-81342c00-e010-11ea-971c-052f78e3f901.png">

**Comment by johnjohndoe** [comment]
HTTP 502 again.

**Comment by DanielRuf** [comment]
> HTTP 502 again.

Confirmed.

![grafik](https://user-images.githubusercontent.com/827205/90383274-3520d000-e080-11ea-84bc-fe7ffa0a83ca.png)

**Comment by oliviertassinari** [comment]
Are there any good alternatives to these badges?

**Comment by DanielRuf** [comment]
@oliviertassinari maybe there are some alternative solutions at https://shields.io/

**Comment by DanielRuf** [comment]
@oliviertassinari maybe there are some alternatives at https://shields.io/

**Comment by oliviertassinari** [comment]
I have removed the badges and added one for https://dependabot.com/.

**Comment by hueitan** [comment]
as of today, it is still down.

**Comment by cyberhck** [comment]
it's down again! also SSL has expired, are there any alternatives to this? I couldn't do it via shields, how about making this a github action instead? At least that would not be down and we can sync every few hours maybe?

Or a lambda function?

**Comment by JustalK** [comment]
I also have my shield all down for david-dm. Do the owner plan to fix the project or should we try to find an alternative ?

**Comment by hodgef** [comment]
I think the service is overloaded and the maintainer doesn't have much time to fix it.
Here some context: https://github.com/alanshaw/david-www/issues/357#issuecomment-278117903

I'm personally looking for an alternative, since the service has been [unreliable for the past few years](https://github.com/alanshaw/david-www/issues?q=is%3Aissue+is%3Aclosed) sadly.

**Comment by arogozine** [comment]
So is shields io pretty much just a proxy for david? Looking for a badge to replace with.

**Comment by calebcartwright** [comment]
> So is shields io pretty much just a proxy for david? Looking for a badge to replace with.

As is the case with all our services, we have to fetch the data from the upstream provider. When you request a GitHub badge from us then we have to fetch the data from GitHub to be able to create the badge, and when you request a David badge from us we have to reach out to the same endpoint discussed here (that's offline). We can't provide badges for services we can't retrieve data from.

https://shields.io/category/dependencies

**Comment by alanshaw** [comment]
I've deployed david to digitalocean apps using the updated dockerfile.

The Letsencrypt API got turned off so a new SSL cert was not issued. I also had to update david so it works with node 14 (was using node 6 before).

SSL certs, OS updates and configuration are now no longer my problem so hooray for that. It also auto deploys. Lets hope it works 🤞
