### ISSUE TITLE
https://david-dm.org/ down.

### ISSUE THREAD

**Issue by abhijeetnarvekar** [alanshaw/david#173]
https://david-dm.org/ seems down
Also certificate shows expired
![Screenshot 2020-11-23 at 09 44 24](https://user-images.githubusercontent.com/17494707/99942758-7a842600-2d70-11eb-9eae-dec1fb4c9475.png)

**Comment by vankasteelj** [comment]
It has been for at least 20 days

**Comment by SudharakaP** [comment]
@alanshaw : If you need help with the deployments and housekeeping this module, I am willing to help in any way I can. Feel free to reach out. 😄

**Comment by Martii** [comment]
TLS is up here with CloudFlare now *(November 25, 2021 expiry)* . david-dm site had a little lag issue but seems to have been found atm. Badge says "unresponsive" on our project... patience can be fun too.

**Comment by alanshaw** [comment]
I've deployed david to digitalocean apps using the updated dockerfile.

The Letsencrypt API got turned off so a new SSL cert was not issued. I also had to update david so it works with node 14 (was using node 6 before).

SSL certs, OS updates and configuration are now no longer my problem so hooray for that. It also auto deploys. Lets hope it works 🤞

**Comment by SudharakaP** [comment]
> I've deployed david to digitalocean apps using the updated dockerfile.
> 
> The Letsencrypt API got turned off so a new SSL cert was not issued. I also had to update david so it works with node 14 (was using node 6 before).
> 
> SSL certs, OS updates and configuration are now no longer my problem so hooray for that. It also auto deploys. Lets hope it works crossed_fingers

Thanks a lot for looking into this. 😄 ❤️

**Comment by jpbernius** [comment]
Thanks for providing and fixing the hosting @alanshaw! We are back with `David` after not even two weeks as we think it can display the dependency status best and most accurate for our project. Awesome tool!
