### ISSUE TITLE
Option to ignore some dependencies

### ISSUE THREAD

**Issue by sindresorhus** [alanshaw/david#63]
I run David on all my modules once in a while and there are some commonly used dependencies that are outdated but that I don't care about updating, like e.g. Mocha. Would be useful if David had an `ignore` option where I could ignore dependencies I don't care about.

**Comment by FGRibreau** [comment]
:+1:

**Comment by rpominov** [comment]
:+1: I think it would be even better if such dependencies could be specified in a file, say `.david-lock` or something.

**Comment by rpominov** [comment]
I've implemented something quick to use in our project: https://github.com/alanshaw/david/compare/master...rpominov:master

Here is our `pakage.json` as an usage example:

```
{
  
  ...

  "scripts": {
    "check-updates": "david || true",
    "update-deps": "david u || true"
  },
  "dependencies": {
    
    ...

  },
  "devDependencies": {
    "david": "rpominov/david#722f8d9546f6944e0b91b71239fdc3320a2870e6"

    ...

  },
  "davidIgnore": [
    "david",
    "react-redux",
    "stats-webpack-plugin"
  ]
}
```

We run `npm run check-updates` to see what needs to be updated, and `npm run update-deps` for actual update.

It works fine for us, but not sure if it good for a PR. I can make a PR, if this makes sense.

**Comment by shellscape** [comment]
:+1: much needed improvement. We have several modules that we'd like to stick with older versions and we'd like not to see a reminder that they're out of date.

**Comment by alanshaw** [comment]
You can now do this with v6.3.0 of david (https://github.com/alanshaw/david#ignore-dependencies).

Enjoy, and let me know if you have any feedback :)

**Comment by sindresorhus** [comment]
@alanshaw I was really looking for a command-line flag, as I want to ignore some dependencies from all packages and I don't want to have to add it to every single package.json. Should I open a new issue?

**Comment by alanshaw** [comment]
Just FYI when calling `getDependencies` or `getUpdatedDependencies` programmatically you can pass it as an option:

```js
david.getUpdatedDependencies(pkg, {ignore: ['async']}, (err, deps) => console.log(deps))
```

...but yes a command line arg would probably also be useful!

**Comment by sindresorhus** [comment]
Alright: https://github.com/alanshaw/david/issues/82

**Comment by rpominov** [comment]
That great! Thank you!

**Comment by shellscape** [comment]
:+1:  thanks for this
