### ISSUE TITLE
semver bug?

### ISSUE THREAD

**Issue by mstuart** [alanshaw/david#76]
I have 4.13, which is >=4.5.  Maybe a bug with how semver is calculated?

![screen shot 2015-07-23 at 10 27 21](https://cloud.githubusercontent.com/assets/742884/8857249/432ccd12-3125-11e5-9565-13504b7cfc2c.png)

https://nodesecurity.io/advisories/express-no-charset-in-content-type-header

Vulnerable: <3.11 || >= 4 <4.5
Patched: >=3.11 <4 || >=4.5

**Comment by alanshaw** [comment]
You have ^4 in your package.json which de-sugars to something like >= 4.0.0 < 5.0.0 which encompasses the vulnerable versions.
