### ISSUE TITLE
Command-line flag for ignoring dependencies

### ISSUE THREAD

**Issue by sindresorhus** [alanshaw/david#82]
Recently an option were introduced to ignore dependencies: https://github.com/alanshaw/david/issues/63

Would be useful if you could pass this on the command-line too.

```
$ david --ignore=mocha --ignore=foo
```

It should be possible to set it multiple times.

**Comment by alanshaw** [comment]
@sindresorhus done - let me know if any problems

**Comment by sindresorhus** [comment]
Works great! Thanks for the quick turnaround @alanshaw :)
