### ISSUE TITLE
Doesn't seem to work with eyeglass package

### ISSUE THREAD

**Issue by strarsis** [alanshaw/david#84]
I used david on a project where package eyeglass is a dependency with version ^0.6.2.
There are now new versions of that package, 0.6.3 and 0.6.4: https://www.npmjs.com/package/eyeglass
However, david doesn't indicate there is a new version for it.

package.json to try (in a new empty folder):
````
{
  "dependencies": {
    "eyeglass": "^0.6.2"
  }
}
````
````
$ david
All dependencies up to date
````

david doesn't indicate there is now latest version 0.6.4 of package eyeglass available.

With best regards

**Comment by alanshaw** [comment]
Hi @strarsis, your dependency isn't out of date according to your version range - ^0.6.2 means >=0.6.2 <0.7.0 so 0.6.3 and 0.6.4 falls within this range. See https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by strarsis** [comment]
Thank you for your answer.

This explains it.
But wouldn't it make sense to opt for the latest version _in that range_?

With best regards

**Comment by strarsis** [comment]
Enhancement proposal: Flag/option to let david select the latest version in a semver _range_.
